version: '2'

services:
  tarantool:
    image: tarantool/tarantool:1.7
    command: tarantool /usr/local/share/tarantool/init.lua
    volumes:
      - $PWD/../../scripts/:/usr/local/share/tarantool
      - $PWD/../../tarantool/:/var/lib/tarantool
    ports:
      - "3301:3301"
    environment:
      TARANTOOL_USER_NAME: admin
      TARANTOOL_USER_PASSWORD: password
      TARANTOOL_PORT: 3301
      TARANTOOL_SLAB_ALLOC_ARENA: 0.1
  usersearchservice:
    image: user/usersearchservice${TAG}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80"
    links:
      - tarantool